#!/usr/bin/env php
<?php

if ( ! defined( 'WP_CONTENT_DIR' ) ) define( 'WP_CONTENT_DIR', __DIR__ . '/../../' );
if ( ! defined( 'ABSPATH' ) ) define( 'ABSPATH', WP_CONTENT_DIR . '/../' );

require_once __DIR__.'/vendor/autoload.php';

/**
 * Ayuco.
 * Commands line scaffolding.
 *
 * @author WordPress MVC <https://www.wordpress-mvc.com/>
 * @license MIT
 * @package wpmvc
 * @version 1.0.7
 */

$ayuco = get_ayuco( __DIR__ );

// BEGIN - Custom commands
// END - Custom commands

$ayuco->interpret();