name: Deploy to GitHub Pages

on:
  push:
    branches: [gh-pages]

env:
  BASE_URL: '/wpmvc/'

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write      # Required to deploy to GitHub Pages
      id-token: write   # Required for OpenID Connect (OIDC) authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21 # Use a compatible Node.js version
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build # The directory Docusaurus builds to

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
