name: Deploy to GitHub Pages

on:
  push:
    branches: [gh-pages]

env:
  BASE_URL: '/wpmvc/'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'yarn' # Or 'npm'
          cache-dependency-path: './package-lock.json' # For npm, or './yarn.lock' for yarn
      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./build # Docusaurus build output
